// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1UTMgsrKIpzbvHO75vyo-bXkcKQF2coQ',
    appId: '1:312823414928:web:502c5d118bf0db0d6cd815',
    messagingSenderId: '312823414928',
    projectId: 'e-commerce-7be3d',
    authDomain: 'e-commerce-7be3d.firebaseapp.com',
    storageBucket: 'e-commerce-7be3d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV3NYFsSkdh-ScEUTlyr6AUVcUcURBTc4',
    appId: '1:312823414928:android:87c4f6ecb5be454b6cd815',
    messagingSenderId: '312823414928',
    projectId: 'e-commerce-7be3d',
    storageBucket: 'e-commerce-7be3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5bfRNDkO7VAV2_ldScgP_jE7nr6MGbcg',
    appId: '1:312823414928:ios:ce7b112d56b5eaf56cd815',
    messagingSenderId: '312823414928',
    projectId: 'e-commerce-7be3d',
    storageBucket: 'e-commerce-7be3d.appspot.com',
    iosBundleId: 'com.example.eShoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5bfRNDkO7VAV2_ldScgP_jE7nr6MGbcg',
    appId: '1:312823414928:ios:ce7b112d56b5eaf56cd815',
    messagingSenderId: '312823414928',
    projectId: 'e-commerce-7be3d',
    storageBucket: 'e-commerce-7be3d.appspot.com',
    iosBundleId: 'com.example.eShoppingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1UTMgsrKIpzbvHO75vyo-bXkcKQF2coQ',
    appId: '1:312823414928:web:220124624caa77286cd815',
    messagingSenderId: '312823414928',
    projectId: 'e-commerce-7be3d',
    authDomain: 'e-commerce-7be3d.firebaseapp.com',
    storageBucket: 'e-commerce-7be3d.appspot.com',
  );
}
